site_name: CHABI Amine sif eddine
site_url: https://amine2000s.github.io/personal-website/
site_description: Personal site of Chabi Amine, a backend-focused computer science enthusiast building with Java, Spring Boot, and more.
repo_url: https://github.com/Amine2000s
repo_name: Amine2000s
#copyright: Copyright &copy; CHABI Amine sif eddine
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Amine2000s
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amine-chabi-a90b7822a/
    - icon: fontawesome/solid/envelope
      link: mailto:chabiaminesifeddine@gmail.com

theme:
  name: material 
  features:
    - navigation.expand
    - navigation.path
    - navigation.footer
    - content.images.zoom
  toc:  
      sticky: true

  

  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode

    - scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  

plugins:
  - blog
  - glightbox


nav:
  - Home: index.md
  - Projects: projects/index.md
  - Blog : blog/index.md
  - Resume: resume.md

markdown_extensions:
    - attr_list
